# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/6"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.synced_folder "data", "/vagrant/data", create: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
   config.vm.provision "shell", inline: <<-SHELL
  # Install relevant packages 
     yum install -y wget curl
     modprobe -a vboxguest vboxsf vboxvideo
  # Get Riak     
     wget http://s3.amazonaws.com/downloads.basho.com/riak/2.2/2.2.0/rhel/6/riak-2.2.0-1.el6.x86_64.rpm
  #   cp riak* /vagrant/data
  # Install Riak 
     yum localinstall -y riak*
  # OS tweak for better Riak performance  
     ulimit -n 65536
  # Minor config update
     echo "buckets.default.allow_mult = true" >> /etc/riak/riak.conf
  # Start Riak  
     riak start
  # Wait for Riak to finish starting up     
     riak-admin wait-for-service riak_kv riak@127.0.0.1
  # Add some test data       
    for i in {0..9}; do
    curl -XPUT http://localhost:8098/riak/docs/foo \
	-H 'Content-Type: text/plain' -d 'demo data goes here';
    curl -XPUT http://localhost:8098/riak/docs/bar \
	-H 'Content-Type: text/plain' -d 'demo demo demo demo';
    curl -XPUT http://localhost:8098/riak/docs/baz \
	-H 'Content-Type: text/plain' -d 'nothing to see here';
    curl -XPUT http://localhost:8098/riak/docs/qux \
	-H 'Content-Type: text/plain' -d 'demo demo';
    curl -XPUT http://localhost:8098/riak/docs/qux \
	-H 'Content-Type: text/plain' -d 'demo data goes here';
    curl -XPUT http://localhost:8098/riak/docs/baz \
	-H 'Content-Type: text/plain' -d 'demo demo demo demo';
    curl -XPUT http://localhost:8098/riak/docs/bar \
	-H 'Content-Type: text/plain' -d 'nothing to see here';
    curl -XPUT http://localhost:8098/riak/docs/foo \
	-H 'Content-Type: text/plain' -d 'demo demo';
done
   SHELL
end
